name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  rust:
    name: Rust (fmt, clippy, check, test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Rustfmt (must be clean)
        run: cargo fmt --all -- --check

      - name: Clippy (no warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Cargo check
        run: cargo check --all-targets --all-features

      - name: Tests
        run: cargo test --all-features --all-targets --locked --workspace

      - name: Doc tests (optional but nice)
        run: cargo test --doc --all-features --locked --workspace