worker_processes 1;
pid /tmp/oxidity-searcher-nginx.pid;
error_log /tmp/oxidity-searcher-nginx-error.log notice;

events {
    worker_connections 128;
}

http {
    access_log /tmp/oxidity-searcher-nginx-access.log;
    default_type application/octet-stream;
    sendfile on;
    server_tokens off;

    include oxidity-searcher-rate-limits.conf;
    include generated/oxidity.io.conf;
    include generated/wallet.oxidity.io.conf;
}
