-- Website/business onboarding persistence removed.
-- This migration is intentionally left as a no-op so existing databases
-- continue to satisfy sqlx migration history without recreating the table.
